version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

  fastapi:
    build: .
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app:my_app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@127.0.0.1:5432/mydb
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"